(function () {
  'use strict';

  const app = angular.module('SantiniGenerator', ['ngSanitize', 'ui.select', 'ui.bootstrap']);

  app.loghi = [
    { name: "Logo vuoto", url: "img/fake_logo.png" },
    { name: "ACTEA  ‐  ARCADIA",                                       url: "img/loghi/ACTEA  ‐  ARCADIA.jpg" },
    { name: "ACTEA ‐ E.A.",                                            url: "img/loghi/ACTEA ‐ E.A..jpg" },
    { name: "ACTEA",                                                   url: "img/loghi/ACTEA.jpg" },
    { name: "AGRARIA 2.0",                                             url: "img/loghi/AGRARIA 2.0.jpg" },
    { name: "AGROINFORMAZIONE",                                        url: "img/loghi/AGROINFORMAZIONE.jpg" },
    { name: "ALGORITMO",                                               url: "img/loghi/ALGORITMO.jpg" },
    { name: "ALIMENTAZIONE",                                           url: "img/loghi/ALIMENTAZIONE.jpg" },
    { name: "ALLEANZA - AZIONE UNIVERSITARIA - CONTROCAMPUS",          url: "img/loghi/ALLEANZA - AZIONE UNIVERSITARIA - CONTROCAMPUS.jpg" },
    { name: "ALLEANZA ‐ CONTROCAMPUS ‐ AZIONE",                        url: "img/loghi/ALLEANZA ‐ CONTROCAMPUS ‐ AZIONE.jpg" },
    { name: "ALLEANZA  ‐  CONTROCAMPUS",                               url: "img/loghi/ALLEANZA  ‐  CONTROCAMPUS.jpg" },
    { name: "ALLEANZA UNIVERSITARIA",                                  url: "img/loghi/ALLEANZA UNIVERSITARIA.jpg" },
    { name: "ALTERNATIVA",                                             url: "img/loghi/ALTERNATIVA.jpg" },
    { name: "ARCADIA ‐ ECONOMIA ATTIVA ‐ O.I.",                        url: "img/loghi/ARCADIA ‐ ECONOMIA ATTIVA ‐ O.I..jpg" },
    { name: "ARCADIA",                                                 url: "img/loghi/ARCADIA.jpg" },
    { name: "ARCADIA - NIKE",                                          url: "img/loghi/ARCADIA - NIKE.jpg" },
    { name: "ARCADIA‐ORIZZONTE ITALIA",                                url: "img/loghi/ARCADIA‐ORIZZONTE ITALIA.jpg" },
    { name: "ARCADIA REVOLUTION",                                      url: "img/loghi/ARCADIA REVOLUTION.jpg" },
    { name: "ARCHÈ",                                                   url: "img/loghi/ARCHÈ.jpg" },
    { name: "ARCHÈ - NIKE - PARTECIPA",                                url: "img/loghi/ARCHÈ - NIKE - PARTECIPA.jpg" },
    { name: "ARES",                                                    url: "img/loghi/ARES.jpg" },
    { name: "ASTRA",                                                   url: "img/loghi/ASTRA.jpg" },
    { name: "AZIONE UNIVERSITARIA AD MAIORA",                          url: "img/loghi/AZIONE UNIVERSITARIA AD MAIORA.jpg" },
    { name: "AZIONE UNIVERSITARIA CONTROCAMPUS",                       url: "img/loghi/AZIONE UNIVERSITARIA CONTROCAMPUS.jpg" },
    { name: "AZIONE UNIVERSITARIA",                                    url: "img/loghi/AZIONE UNIVERSITARIA.jpg" },
    { name: "CITING",                                                  url: "img/loghi/CITING.jpg" },
    { name: "CONTROCAMPUS",                                            url: "img/loghi/CONTROCAMPUS.jpg" },
    { name: "CONTROCAMPUS ‐ POPOLO DEGLI STUDENTI ‐ ARES",             url: "img/loghi/CONTROCAMPUS ‐ POPOLO DEGLI STUDENTI ‐ ARES.jpg" },
    { name: "CONTROCAMPUS ‐ POPOLO DEGLI STUDENTI",                    url: "img/loghi/CONTROCAMPUS ‐ POPOLO DEGLI STUDENTI.jpg" },
    { name: "CREAZIONE GIOVANE",                                       url: "img/loghi/CREAZIONE GIOVANE.jpg" },
    { name: "CREDIAMOCI ‐ ARES",                                       url: "img/loghi/CREDIAMOCI ‐ ARES.jpg" },
    { name: "CREDIAMOCI",                                              url: "img/loghi/CREDIAMOCI.jpg" },
    { name: "DESTRA UNIVERSITARIA",                                    url: "img/loghi/DESTRA UNIVERSITARIA.jpg" },
    { name: "DMI INSIDER",                                             url: "img/loghi/DMI INSIDER.png" },
    { name: "DOTTORANDI SCIENZE CHIMICHE",                             url: "img/loghi/DOTTORANDI SCIENZE CHIMICHE.jpg" },
    { name: "EBLA",                                                    url: "img/loghi/EBLA.jpg" },
    { name: "ECONOMIA ATTIVA",                                         url: "img/loghi/ECONOMIA ATTIVA.jpg" },
    { name: "EUREKA",                                                  url: "img/loghi/EUREKA.jpg" },
    { name: "FUTURA SANITÀ",                                           url: "img/loghi/FUTURA SANITÀ.jpg" },
    { name: "GATTI FISICI",                                            url: "img/loghi/GATTI FISICI.jpg" },
    { name: "GIOVANI CIDEC",                                           url: "img/loghi/GIOVANI CIDEC.jpg" },
    { name: "GIOVANI CIDEC  ‐  LA FINESTRA",                           url: "img/loghi/GIOVANI CIDEC  ‐  LA FINESTRA.jpg" },
    { name: "GIURISTI UNICT",                                          url: "img/loghi/GIURISTI UNICT.jpg" },
    { name: "I LETTERATI DEL DISUM",                                   url: "img/loghi/I LETTERATI DEL DISUM.jpg" },
    { name: "IL FUTURO DELLA SCIENZA ‐ CONTROCAMPUS",                  url: "img/loghi/IL FUTURO DELLA SCIENZA ‐ CONTROCAMPUS.jpg" },
    { name: "IN CAMPO PER IL DISUM ‐ CONTROCAMPUS",                    url: "img/loghi/IN CAMPO PER IL DISUM ‐ CONTROCAMPUS.jpg" },
    { name: "INFERMIERISTICAMENTE",                                    url: "img/loghi/INFERMIERISTICAMENTE.jpg" },
    { name: "INFOLEX",                                                 url: "img/loghi/INFOLEX.jpg" },
    { name: "INFORMAZIONE",                                            url: "img/loghi/INFORMAZIONE.jpg" },
    { name: "INGEGNERIATTIVA",                                         url: "img/loghi/INGEGNERIATTIVA.jpg" },
    { name: "INSIEME",                                                 url: "img/loghi/INSIEME.jpg" },
    { name: "INSIEME PER IL DISUM",                                    url: "img/loghi/INSIEME PER IL DISUM.jpg" },
    { name: "IRIDE",                                                   url: "img/loghi/IRIDE.jpg" },
    { name: "KOINÈ ARCADIA",                                           url: "img/loghi/KOINÈ ARCADIA.jpg" },
    { name: "KOINÈ",                                                   url: "img/loghi/KOINÈ.jpg" },
    { name: "LA FINESTRA - ACTEA",                                     url: "img/loghi/LA FINESTRA - ACTEA.jpg" },
    { name: "LA FINESTRA ‐ KOINÈ",                                     url: "img/loghi/LA FINESTRA ‐ KOINÈ.jpg" },
    { name: "LA FINESTRA ‐ LIBERI DI SCEGLIERE",                       url: "img/loghi/LA FINESTRA ‐ LIBERI DI SCEGLIERE.jpg" },
    { name: "LAYOUT",                                                  url: "img/loghi/LAYOUT.jpg" },
    { name: "LEX",                                                     url: "img/loghi/LEX.jpg" },
    { name: "LIBERA UNIVERSITÀ",                                       url: "img/loghi/LIBERA UNIVERSITÀ.jpg" },
    { name: "LIBERTÀ È PARTECIPAZIONE",                                url: "img/loghi/LIBERTÀ È PARTECIPAZIONE.jpg" },
    { name: "LIBERTAS ‐ IRIDE",                                        url: "img/loghi/LIBERTAS ‐ IRIDE.jpg" },
    { name: "LIBERTAS",                                                url: "img/loghi/LIBERTAS.jpg" },
    { name: "LIBERTAS ‐ LIBERI E FORTI ‐ ARES",                        url: "img/loghi/LIBERTAS ‐ LIBERI E FORTI ‐ ARES.jpg" },
    { name: "LIBERTAS‐SANILAB",                                        url: "img/loghi/LIBERTAS‐SANILAB.jpg" },
    { name: "LINK ‐ STUDENTI INDIPENDENTI",                            url: "img/loghi/LINK ‐ STUDENTI INDIPENDENTI.jpg" },
    { name: "MEDICAMENTE",                                             url: "img/loghi/MEDICAMENTE.jpg" },
    { name: "MEGALIDEA",                                               url: "img/loghi/MEGALIDEA.jpg" },
    { name: "M.S.U. EVOLUTION",                                        url: "img/loghi/M.S.U. EVOLUTION.jpg" },
    { name: "NIKE ATTIVA",                                             url: "img/loghi/NIKE ATTIVA.jpg" },
    { name: "NIKE",                                                    url: "img/loghi/NIKE.jpg" },
    { name: "NOI",                                                     url: "img/loghi/NOI.jpg" },
    { name: "NO STRESS",                                               url: "img/loghi/NO STRESS.jpg" },
    { name: "NUCLEO ATTIVO",                                           url: "img/loghi/NUCLEO ATTIVO.jpg" },
    { name: "NUOVA GENERAZIONE",                                       url: "img/loghi/NUOVA GENERAZIONE.jpg" },
    { name: "NUOVA IBLA",                                              url: "img/loghi/NUOVA IBLA.jpg" },
    { name: "old LIBERTAS LIBERI E FORTI",                             url: "img/loghi/old LIBERTAS LIBERI E FORTI.jpg" },
    { name: "OLTRE",                                                   url: "img/loghi/OLTRE.jpg" },
    { name: "ORIZZONTE ITALIA",                                        url: "img/loghi/ORIZZONTE ITALIA.jpg" },
    { name: "PARTECIPA",                                               url: "img/loghi/PARTECIPA.jpg" },
    { name: "PARTITO DEMOCRATICO - LA FINESTRA - SI CAMBIA",           url: "img/loghi/PARTITO DEMOCRATICO - LA FINESTRA - SI CAMBIA.jpg" },
    { name: "PARTITO DEMOCRATICO - STUDENTI DEMOCRATICI",              url: "img/loghi/PARTITO DEMOCRATICO - STUDENTI DEMOCRATICI.jpg" },
    { name: "PCG ‐ PER CIÒ CHE È GIUSTO",                              url: "img/loghi/PCG ‐ PER CIÒ CHE È GIUSTO.jpg" },
    { name: "PHARMA",                                                  url: "img/loghi/PHARMA.jpg" },
    { name: "PHYSICS INSIDERS",                                        url: "img/loghi/PHYSICS INSIDERS.jpg" },
    { name: "POPOLARI E SOVRANISTI",                                   url: "img/loghi/POPOLARI E SOVRANISTI.jpg" },
    { name: "POPOLO DEGLI STUDENTI",                                   url: "img/loghi/POPOLO DEGLI STUDENTI.jpg" },
    { name: "PROGETTIAMO CIVILE",                                      url: "img/loghi/PROGETTIAMO CIVILE.jpg" },
    { name: "PROGETTO DEGLI UNIVERSITARI",                             url: "img/loghi/PROGETTO DEGLI UNIVERSITARI.jpg" },
    { name: "PROGETTO PER AGRARIA",                                    url: "img/loghi/PROGETTO PER AGRARIA.jpg" },
    { name: "PROGETTO PER ALIMENTARI",                                 url: "img/loghi/PROGETTO PER ALIMENTARI.jpg" },
    { name: "PROGETTO PER IL DI3A",                                    url: "img/loghi/PROGETTO PER IL DI3A.jpg" },
    { name: "REVOLUTION",                                              url: "img/loghi/REVOLUTION.jpg" },
    { name: "RIAVVIAMO AGRARIA",                                       url: "img/loghi/RIAVVIAMO AGRARIA.jpg" },
    { name: "RISE",                                                    url: "img/loghi/RISE.jpg" },
    { name: "SANILAB",                                                 url: "img/loghi/SANILAB.jpg" },
    { name: "SI! ‐ STUDENTI INDIPENDENTI",                             url: "img/loghi/SI! ‐ STUDENTI INDIPENDENTI.jpg" },
    { name: "SOCIAL",                                                  url: "img/loghi/SOCIAL.jpg" },
    { name: "SOGNO CIVILE",                                            url: "img/loghi/SOGNO CIVILE.jpg" },
    { name: "S.O.S. ERSU - ARCHÈ - UNIVERSITÀ POPOLARE",               url: "img/loghi/S.O.S. ERSU - ARCHÈ - UNIVERSITÀ POPOLARE.jpg" },
    { name: "SOS ERSU",                                                url: "img/loghi/SOS ERSU.jpg" },
    { name: "SPACE WINDOW",                                            url: "img/loghi/SPACE WINDOW.jpg" },
    { name: "STUDENTI DEMOCRATICI",                                    url: "img/loghi/STUDENTI DEMOCRATICI.jpg" },
    { name: "STUDENTI DI FILOSOFIA ‐ UNICT",                           url: "img/loghi/STUDENTI DI FILOSOFIA ‐ UNICT.jpg" },
    { name: "STUDENTI",                                                url: "img/loghi/STUDENTI.jpg" },
    { name: "STUDENTI PER LE LIBERTÀ",                                 url: "img/loghi/STUDENTI PER LE LIBERTÀ.jpg" },
    { name: "STUDENTI PER SCIENZE DELLA FORMAZIONE",                   url: "img/loghi/STUDENTI PER SCIENZE DELLA FORMAZIONE.jpg" },
    { name: "STUDENTI UNICT",                                          url: "img/loghi/STUDENTI UNICT.jpg" },
    { name: "SUPPORTO STUDENTI",                                       url: "img/loghi/SUPPORTO STUDENTI.jpg" },
    { name: "SVEGLIATI UNIVERSITÀ",                                    url: "img/loghi/SVEGLIATI UNIVERSITÀ.jpg" },
    { name: "UDU  ‐  UNIONE DEGLI UNIVERSITARI",                       url: "img/loghi/UDU  ‐  UNIONE DEGLI UNIVERSITARI.jpg" },
    { name: "UNI DISUM",                                               url: "img/loghi/UNI DISUM.jpg" },
    { name: "UNITI PER ARCHITETTURA",                                  url: "img/loghi/UNITI PER ARCHITETTURA.jpg" },
    { name: "UNITI PER I FUORI SEDE PER LE CASE DELLO STUDENTE-LISTA DIRITTO ALLO STUDIO", url: "img/loghi/UNITI PER I FUORI SEDE PER LE CASE DELLO STUDENTE-LISTA DIRITTO ALLO STUDIO.jpg" },
    { name: "UNIVERSITÀ POPOLARE",                                     url: "img/loghi/UNIVERSITÀ POPOLARE.jpg" },
    { name: "UnivErsu - NOI PER IL DIRITTO ALLO STUDIO",               url: "img/loghi/UnivErsu - NOI PER IL DIRITTO ALLO STUDIO.jpg" },
    { name: "UNYDEA",                                                  url: "img/loghi/UNYDEA.jpg" },
    { name: "VOLJA",                                                   url: "img/loghi/VOLJA.jpg" },
    { name: "WE LOVE UNICT",                                           url: "img/loghi/WE LOVE UNICT.jpg" },
  ];

}());
